# captura/exceptions.py

class InvalidDataError(Exception):
    """
    Exceção lançada quando algum dado capturado não puder
    ser convertido ou for considerado inválido.
    """
    pass